# Generated by Django 5.1.6 on 2025-02-22 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('salary', 'Salary'), ('freelance', 'Freelance'), ('investment', 'Investment'), ('other', 'Other'), ('food', 'Food'), ('transportation', 'Transportation'), ('entertainment', 'Entertainment'), ('bills', 'Bills'), ('other', 'Other')], max_length=50),
        ),
    ]
